project_name: gitconfigs
builds:
  - id: gitconfigs
    main: ./cmd
    binary: gitconfigs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
